STRING(o,"instance",_instance)
STRING(o,"delivery-method",_deliveryMethod)
STRING(o,"sri-sm-opc",_sriSmOpc)
STRING(o,"sri-sm-dpc",_sriSmDpc)
STRING(o,"sri-sm-sccp-calling-address",_sriSmSccpCallingAddress)
STRING(o,"sri-sm-sccp-called-address-prefix",_sriSmSccpCalledAddressPrefix)
STRING(o,"sri-sm-sccp-called-address-replacement",_sriSmSccpCalledAddressReplacement)
INTEGER(o,"sri-sm-sccp-called-translation-table",_sriSmSccpCalledTranslationTable)
STRING(o,"sri-sm-gsm-map-smsc-address",_sriSmGsmMapSmscAddress)

STRING(o,"forward-sm-opc",_forwardSmOpc)
STRING(o,"forward-sm-dpc",_forwardSmDpc)
STRING(o,"forward-sm-sccp-calling-address",_forwardSmSccpCallingAddress)
STRING(o,"forward-sm-sccp-called-address-prefix",_forwardSmSccpCalledAddressPrefix)
STRING(o,"forward-sm-sccp-called-address-replacement",_forwardSmSccpCalledAddressReplacement)
INTEGER(o,"forward-sm-sccp-called-translation-table",_forwardSmSccpCalledTranslationTable)
STRING(o,"forward-sm-gsm-map-smsc-address",_forwardSmGsmMapSmscAddress)

STRING(o,"replace-sender-id",_fixedSenderId)
STRING(o,"msc-from",_mscFrom)
INTEGER(o,"priority",_priority)
STRING(o,"timezone",_timezone)
STRING(o,"ts",_ts)
DOUBLE(o,"max-submission-speed",_maxSubmissionSpeed)
INTEGER(o,"max-attempts",_maxAttempts)
INTEGER(o,"max-attempts-for-delivery-reports",_maxAttemptsDlr)
STRING(o,"retry-pattern",_retryPattern)


BOOLEAN(o,"config-api-access",_apiAccess)
BOOLEAN(o,"web-access",_webSubmissionAccess)
BOOLEAN(o,"web-admin-access",_webAdminAccess)
BOOLEAN(o,"smpp-access",_smppAccess)
BOOLEAN(o,"emiucp-access",_emiucpAccess)

    
STRING(o,"categorizer",_categorizer)
STRING(o,"pre-routing-filter",_preRoutingFilter)
STRING(o,"pre-billing-filter",_preBillingFilter)
STRING(o,"routing-engine",_routingEngine)
STRING(o,"post-routing-filter",_postRoutingFilter)
STRING(o,"post-billing-filter",_postBillingFilter)
STRING(o,"delivery-report-filter",_deliveryReportFilter)
STRING(o,"cdr-writer-plugin",_cdrWriter)
STRING(o,"storage-engine",_storageEngine)
