STRING(s,"attach-to",_attachTo,"attach_to",10)
STRING(s,"number",_number,"number",11)
STRING(s,"imsi-pool",_imsiPool,"imsi_pool",12)
DOUBLE(s,"timeout",_timeout,"timeout",13)
INTEGER(s,"answer-translation-type",_answerTranslationType,"answer_translation_type",14)
