STRING(o,"mtp3-linkset",_mtp3LinkSet)
STRING(o,"m2pa",_m2pa)
INTEGER(o,"slc",_slc)
DOUBLE(o,"link-test-time",_linkTestTime)
DOUBLE(o,"link-test-ack-time",_linkTestAckTime)
DOUBLE(o,"reopen-timer1",_reopenTimer1)
DOUBLE(o,"reopen-timer2",_reopenTimer2)

INTEGER(o,"m2pa-window-size",_m2pa_windowSize)
DOUBLE(o,"m2pa-t1",_m2pa_t1)
DOUBLE(o,"m2pa-t2",_m2pa_t2)
DOUBLE(o,"m2pa-t3",_m2pa_t3)
DOUBLE(o,"m2pa-t4e",_m2pa_t4e)
DOUBLE(o,"m2pa-t4n",_m2pa_t4n)
DOUBLE(o,"m2pa-t5",_m2pa_t5)
DOUBLE(o,"m2pa-t6",_m2pa_t6)
DOUBLE(o,"m2pa-t7",_m2pa_t7)
STRING(o,"m2pa-state-machine-log",_m2pa_stateMachineLog)

ARRAY_VERBOSE(o,"sctp-local-ip",_sctp_localAddresses)
ARRAY_VERBOSE(o,"sctp-remote-ip",_sctp_remoteAddresses)
INTEGER(o,"sctp-local-port",_sctp_localPort)
INTEGER(o,"sctp-remote-port",_sctp_remotePort)
BOOLEAN(o,"sctp-allow-any-remote-port-inbound",_sctp_allowAnyRemotePortIncoming)
BOOLEAN(o,"sctp-passive",_sctp_passive)
DOUBLE(o,"sctp-heartbeat",_sctp_heartbeat)
INTEGER(o,"sctp-mtu",_sctp_mtu)
INTEGER(o,"sctp-max-init-timeout",_sctp_maxInitTimeout)
INTEGER(o,"sctp-max-init-attempts",_sctp_maxInitAttempts)

