STRING(o,"attach-to",_attachTo)
STRING(o,"number",_number)
DOUBLE(o,"timeout",_timeout)
STRING(o,"timeout-trace-directory",_timeoutTraceDirectory)
STRING(o,"full-trace-directory",_fullTraceDirectory)
