ARRAY(o,"local-ip",_localAddresses)
ARRAY(o,"remote-ip",_remoteAddresses)
INTEGER(o,"local-port",_localPort)
INTEGER(o,"remote-port",_remotePort)
BOOLEAN(o,"sctp-over-tcp",_sctpOverTcp)
STRING(o,"sctp-over-tcp-session-key",_sctpOverTcpSessionKey)
BOOLEAN(o,"allow-any-remote-port-inbound",_allowAnyRemotePortIncoming)
BOOLEAN(o,"passive",_passive)
DOUBLE(o,"heartbeat",_heartbeat)
INTEGER(o,"mtu",_mtu)
INTEGER(o,"max-init-timeout",_maxInitTimeout)
INTEGER(o,"max-init-attempts",_maxInitAttempts)
INTEGER(o,"min-receive-buffer-size",_minReceiveBufferSize)
INTEGER(o,"min-send-buffer-size",_minSendBufferSize)
STRING(o,"dscp",_dscp)
BOOLEAN(o,"use-peeloff",_usePeelOff)

