STRING(o,"instance",_instance,"instance",10,"")
STRING(o,"delivery-method",_deliveryMethod,"delivery_method",11,"")
STRING(o,"sri-sm-opc",_sriSmOpc,"sri_sm_opc",12,"")
STRING(o,"sri-sm-dpc",_sriSmDpc,"sri_sm_dpc",13,"")
STRING(o,"sri-sm-sccp-calling-address",_sriSmSccpCallingAddress,"sri_sm_sccp_calling_address",14,"")
STRING(o,"sri-sm-sccp-called-address-prefix",_sriSmSccpCalledAddressPrefix,"sri_sm_scpp_calle_address_prefix",15,"")
STRING(o,"sri-sm-sccp-called-address-replacement",_sriSmSccpCalledAddressReplacement,"sri_sm_sccp_called_address_replacement",16,"")
INTEGER(o,"sri-sm-sccp-called-translation-table",_sriSmSccpCalledTranslationTable,"sri_sm_sccp_called_trannslation_table",17,"")
STRING(o,"sri-sm-gsm-map-smsc-address",_sriSmGsmMapSmscAddress,"sri_sm_gsm_map_smsc_address",18,"")

STRING(o,"forward-sm-opc",_forwardSmOpc,"forward_sm_opc",19,"")
STRING(o,"forward-sm-dpc",_forwardSmDpc,"forward_sm_dpc",20,"")
STRING(o,"forward-sm-sccp-calling-address",_forwardSmSccpCallingAddress,"forward_sm_sccp_calling_address",21,"")
STRING(o,"forward-sm-sccp-called-address-prefix",_forwardSmSccpCalledAddressPrefix,"forward_sm_sccp_called_address_prefix",22,"")
STRING(o,"forward-sm-sccp-called-address-replacement",_forwardSmSccpCalledAddressReplacement,"forward_sm_sccp_called_address_replacement",23,"")
INTEGER(o,"forward-sm-sccp-called-translation-table",_forwardSmSccpCalledTranslationTable,"forward_sm_sccp_called_translation_table",24,"")
STRING(o,"forward-sm-gsm-map-smsc-address",_forwardSmGsmMapSmscAddress,"forward_sm_gsm_map_smsc_address",25,"")

STRING(o,"replace-sender-id",_fixedSenderId,"replace_sender_id",26,"")
STRING(o,"msc-from",_mscFrom,"msc_from",27,"")
INTEGER(o,"priority",_priority,"priority",28,"")
STRING(o,"timezone",_timezone,"timezone",29,"")
STRING(o,"ts",_ts,"ts",30,"")
DOUBLE(o,"max-submission-speed",_maxSubmissionSpeed,"max_submission_speed",31,"")
INTEGER(o,"max-attempts",_maxAttempts,"max_attempts",32,"")
INTEGER(o,"max-attempts-for-delivery-reports",_maxAttemptsDlr,"max_attempts_for_delivery_reports",33,"")
STRING(o,"retry-pattern",_retryPattern,"retry_pattern",34,"")


BOOLEAN(o,"config-api-access",_apiAccess,"config_api_access",35,"")
BOOLEAN(o,"web-access",_webSubmissionAccess,"web_access",36,"")
BOOLEAN(o,"web-admin-access",_webAdminAccess,"web_admin_access",37,"")
BOOLEAN(o,"smpp-access",_smppAccess,"smpp_access",38,"")
BOOLEAN(o,"emiucp-access",_emiucpAccess,"emiupc_access",39,"")

    
STRING(o,"categorizer",_categorizer,"categorizer",40,"")
STRING(o,"pre-routing-filter",_preRoutingFilter,"pre_routing_filter",41,"")
STRING(o,"pre-billing-filter",_preBillingFilter,"pre_billing_filter",42,"")
STRING(o,"routing-engine",_routingEngine,"routing_engine",43,"")
STRING(o,"post-routing-filter",_postRoutingFilter,"post_routing_filter",44,"")
STRING(o,"post-billing-filter",_postBillingFilter,"post_billing_filter",45,"")
STRING(o,"delivery-report-filter",_deliveryReportFilter,"delivery_report_filter",46,"")
STRING(o,"cdr-writer-plugin",_cdrWriter,"cdr_writer_plugin",47,"")
STRING(o,"storage-engine",_storageEngine,"storage_engine",48,"")
