
STRING(o,"host",_host,"host",10,"")
STRING(o,"database-name",_databaseName,"database_name",11,"")
STRING(o,"driver",_driver,"driver",12,"")
STRING(o,"user",_user,"user",13,"")
STRING(o,"pass",_pass,"pass",14,"encrypt")
INTEGER(o,"port",_port,"port",15,"")
INTEGER(o,"min-sessions",_minSessions,"min_sessions",16,"")
INTEGER(o,"max-sessions",_maxSessions,"max_sessions",17,"")
STRING(o,"socket",_socket,"socket",18,"")
DOUBLE(o,"ping-intervall",_pingIntervall,"ping_intervall",19,"")
STRING(o,"storage-type",_storageType,"storage_type",20,"")
STRING(o,"version",_version,"version",21,"")
STRING(o,"encryption-key",_encryptionKey,"encryption_key",22,"nodb")

