STRING(o,"attach-to",_attachTo,"attach_to",10,"")
STRING(o,"address",_address,"address",11,"")
STRING(o,"ssn",_ssn,"ssn",12,"")
DOUBLE(o,"timeout",_timeout,"timeout",13,"")
STRING(o,"operations",_operations,"operations",14,"")
