STRING(o,"attach-to",_attachTo,"attach_to",10,"")
STRING(o,"number",_number,"number",11,"")
STRING(o,"full-trace-directory",_fullTraceDirectory,"full_trace_directory",12,"")
STRING(o,"timeout-trace-directory",_timeoutTraceDirectory,"timeout_trace_directory",13,"")
INTEGER(o,"smsc-translation-type",_smscTranslationType,"smsc_translation_type",14,"")
INTEGER(o,"srism-translation-type",_srismTranslationType,"srism_translation_type",15,"")
INTEGER(o,"forwardsm-translation-type",_forwardsmTranslationType,"forwardsms_translation_type",16,"")
REAL(o,"timeout",_timeout,"timeout",17,"")
INTEGER(o,"default-called-tt"      ,_defaultCalledTT      ,"default_called_tt"      ,117,"")
